const LOCALE_GERMAN = 'de'
const LOCALE_ENGLISH = 'en'
const LOCALE_FRENCH = 'fr'
const LOCALE_POLISH = 'pl'
const LOCALE_DANISH = 'dk'
const DEFAULT_LOCALE = LOCALE_ENGLISH

const SUPPORTED_LOCALES = [
  [LOCALE_ENGLISH, 'English'],
  [LOCALE_GERMAN, 'Deutsch'],
  [LOCALE_FRENCH, 'Français'],
  [LOCALE_POLISH, 'Polski'],
  [LOCALE_DANISH, 'Dansk']
]

module.exports = {
  LOCALE_GERMAN,
  LOCALE_ENGLISH,
  LOCALE_FRENCH,
  LOCALE_POLISH,
  LOCALE_DANISH,
  DEFAULT_LOCALE,
  SUPPORTED_LOCALES
}
